// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  sessionId: __t.u64().name("session_id"),
  initiatorPersonaId: __t.u64().name("initiator_persona_id"),
  partnerPersonaId: __t.u64().name("partner_persona_id"),
  partnerDisplayName: __t.string().name("partner_display_name"),
  status: __t.string(),
  signalStrength: __t.u32().name("signal_strength"),
  turnCount: __t.u32().name("turn_count"),
  controlMode: __t.string().name("control_mode"),
  humanPersonaId: __t.option(__t.u64()).name("human_persona_id"),
  reason: __t.option(__t.string()),
  rank: __t.option(__t.u32()),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
