// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  owner: __t.identity(),
  initiatorPersonaId: __t.u64().name("initiator_persona_id"),
  status: __t.string(),
  totalConversations: __t.u32().name("total_conversations"),
  startedAt: __t.timestamp().name("started_at"),
  deadlineMicros: __t.u64().name("deadline_micros"),
  createdAt: __t.timestamp().name("created_at"),
});
