// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AppendMessageReducer from "../append_message_reducer";
import ArchiveConversationReducer from "../archive_conversation_reducer";
import CompleteConversationReducer from "../complete_conversation_reducer";
import CreatePersonaReducer from "../create_persona_reducer";
import FinalizeSessionReducer from "../finalize_session_reducer";
import PingPresenceReducer from "../ping_presence_reducer";
import RegisterOrchestratorReducer from "../register_orchestrator_reducer";
import ReleaseConversationReducer from "../release_conversation_reducer";
import SendHumanMessageReducer from "../send_human_message_reducer";
import SendMatchMessageReducer from "../send_match_message_reducer";
import StartMatchReducer from "../start_match_reducer";
import TakeOverConversationReducer from "../take_over_conversation_reducer";
import UpdateSignalReducer from "../update_signal_reducer";

export type AppendMessageParams = __Infer<typeof AppendMessageReducer>;
export type ArchiveConversationParams = __Infer<typeof ArchiveConversationReducer>;
export type CompleteConversationParams = __Infer<typeof CompleteConversationReducer>;
export type CreatePersonaParams = __Infer<typeof CreatePersonaReducer>;
export type FinalizeSessionParams = __Infer<typeof FinalizeSessionReducer>;
export type PingPresenceParams = __Infer<typeof PingPresenceReducer>;
export type RegisterOrchestratorParams = __Infer<typeof RegisterOrchestratorReducer>;
export type ReleaseConversationParams = __Infer<typeof ReleaseConversationReducer>;
export type SendHumanMessageParams = __Infer<typeof SendHumanMessageReducer>;
export type SendMatchMessageParams = __Infer<typeof SendMatchMessageReducer>;
export type StartMatchParams = __Infer<typeof StartMatchReducer>;
export type TakeOverConversationParams = __Infer<typeof TakeOverConversationReducer>;
export type UpdateSignalParams = __Infer<typeof UpdateSignalReducer>;

