// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  conversationId: __t.u64().name("conversation_id"),
  sessionId: __t.u64().name("session_id"),
  initiatorOwner: __t.identity().name("initiator_owner"),
  partnerOwner: __t.identity().name("partner_owner"),
  orchestratorIdentity: __t.identity().name("orchestrator_identity"),
  senderPersonaId: __t.u64().name("sender_persona_id"),
  senderName: __t.string().name("sender_name"),
  content: __t.string(),
  source: __t.string(),
  seq: __t.u32(),
  createdAt: __t.timestamp().name("created_at"),
});
